Terraform 가이드 수정
TOAST-DOCS/Compute-Instance pull request #17
Opened 2021-05-21 09:15 UTC by tskim-nhn

* 테라폼 cinderv3 카탈로그 이슈로 인한 volume attach 이슈 임시 수정
* Terraform 초기화에 사용되는 provider.tf 업데이트
* 구버전 이미지 업데이트
* Terraform cli 에서 출력되는 문 update

관련 업무: https://nhnent.dooray.com/project/posts/2972364102752243069

2021-05-23 23:33 UTC, 5bpa requested changes

2021-05-23 23:33 UTC, 5bpa commented on ko/terraform-guide.md
> +Data sources는 `{data sources 자원 유형}.{data source 이름}`으로 참조합니다. 아래 예제에서는 `openstack_images_image_v2.ubuntu_2004_20201222`로 가져온 이미지 정보를 참조합니다.
`NHN Cloud는 주기적으로 이미지를 업데이트하므로 이미지 이름이 변경될 수 있습니다. 사용하고자 하는 정확한 이미지 이름은 콘솔을 참조하여 명시합니다.`
를 문단 끝에 추가합시다.

2021-05-23 23:33 UTC, 5bpa commented on ko/terraform-guide.md
> +  name = "Ubuntu Server 20.04.1 LTS (2020.12.22)"  # 최신 ubuntu 버전 명시
최신 버전만 명시해야 하는 것은 아니니, 주석은 제외하도록 하지요.

2021-05-23 23:33 UTC, 5bpa commented on ko/terraform-guide.md
> +  name = "Ubuntu Server 20.04.1 LTS (2020.12.22)"  # 최신 ubuntu 버전 명시
마찬가지로 주석은 제외하도록 하지요.

2021-05-23 23:33 UTC, 5bpa commented on ko/terraform-guide.md
> +  name = "Windows 2019 STD with MS-SQL 2019 Standard (2020.12.22) KO"  # 최신 windows 버전 명시
마찬가지로 주석은 제외하도록 하지요.

2021-05-23 23:33 UTC, 5bpa commented on ko/terraform-guide.md
> +  image_id = data.openstack_images_image_v2.centos_78_20210223.id  # 최신 CentOS 버전 명시
마찬가지로 주석은 제외하도록 하지요.

2021-05-24 02:04 UTC, tskim-nhn commented on ko/terraform-guide.md
> +Data sources는 `{data sources 자원 유형}.{data source 이름}`으로 참조합니다. 아래 예제에서는 `openstack_images_image_v2.ubuntu_2004_20201222`로 가져온 이미지 정보를 참조합니다.
수정된 문단의 윗 문단 끝에 추가하겠습니다.

2021-05-24 06:09 UTC, 5bpa approved these changes
:+1:

2021-05-25 03:13 UTC, merged